# Generated by Django 4.2.4 on 2023-08-31 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название места'),
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=25, verbose_name='Токен')),
                ('connected_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='connected_by_token', to='bot.tguser', verbose_name='Присоединившийся')),
                ('token_creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='token_creator', to='bot.tguser', verbose_name='Создатель токена')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
    ]
