# Generated by Django 4.2.4 on 2023-08-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_point_name_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='admin_check',
            field=models.BooleanField(blank=True, default=False, verbose_name='Админ ли новый пользователь?'),
        ),
    ]
