# Generated by Django 4.2.4 on 2023-08-31 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_tokens_active_token_alter_tguser_admin_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='connected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='connected_by_token', to='bot.tguser', verbose_name='Присоединившийся'),
        ),
    ]
