# Generated by Django 4.2.4 on 2023-09-01 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_tokens_connected_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания токена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokens',
            name='joined_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='joined_user', to='bot.tguser', verbose_name='Присоединившийся пользователь'),
        ),
    ]
