# Generated by Django 4.2.4 on 2023-09-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_tokens_creation_time_tokens_joined_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='activated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Был ли токен использован'),
        ),
    ]
