# Generated by Django 4.2.4 on 2023-09-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_tokens_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Был ли токен использован'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='joined_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='joined_user', to='bot.tguser', verbose_name='Присоединившийся пользователь'),
        ),
    ]
