# Generated by Django 4.2.4 on 2023-09-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_tokens_activated_alter_tokens_joined_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='joined_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_user', to='bot.tguser', verbose_name='Присоединившийся пользователь'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_creator', to='bot.tguser', verbose_name='Создатель токена'),
        ),
    ]
