# Generated by Django 4.2.4 on 2023-09-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_tokens_joined_user_alter_tokens_token_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание места'),
        ),
    ]
