# Generated by Django 4.2.4 on 2023-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_point_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='navigator_link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на навигатор'),
        ),
    ]
